# Change these first
owner: Hell13Cat # Your GitHub organization or username, where this repository lives
repo: status-page  # The name of this repository

sites:
  - name: VTuber List
    url: https://vt-db.nekono.su
  - name: Sorters
    url: https://sorters.nekono.su

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nekono.su
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nya Uptime
  introTitle: "**Nya Uptime** service for checking the operation of Nekono services"
  introMessage: ""
  navbar:
    - title: Nya Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
